### ISSUE TITLE
Outdated version of ratatui

### ISSUE THREAD

**Issue by SkwalExe** [7sDream/tui-markup#2]
Hi, this library looks very promising but I am facing a small problem.

I cannot use this library in my application because it uses Ratatui v0.28 while this library only supports Ratatui versions up to 0.26.

Will the dependencies get updated? I can create a pull request if needed.
Thanks in advance. Léopold Koprivnik.

**Comment by 7sDream** [comment]
Of course, dependencies upgrade PRs are welcome!

**Comment by 7sDream** [comment]
@SkwalExe 0.5.0 just released.
