### ISSUE TITLE
How to not ignore whitespace after tag list

### ISSUE THREAD

**Issue by SkwalExe** [7sDream/tui-markup#4]
I want to print a word with a red background and a space on each side to create a "block". It should look like this (first line):
![image](https://github.com/user-attachments/assets/fc9691eb-231a-40bf-aeaf-480bb204c1fa)

But the whitespace after the tag list is ignored and I have no way to accomplish that. printing `<bgred Error >` or `<bgred     error >` looks like this : 
![image](https://github.com/user-attachments/assets/000de77e-7784-4d20-b094-9b8d7c48cb89)

How can I explicitly add a space before the text?

**Comment by 7sDream** [comment]
I think the space after the taglist(except the one as sep) is not ignored, Just add a (extra) space before "Error " should work.

![图片](https://github.com/user-attachments/assets/1277dec2-21d5-43e8-b396-a693372fb64d)

Does this works for you?

**Comment by SkwalExe** [comment]
After digging around a little more I found out the leading white space was removed by Ratatui's Paragraph. Adding the option `trim: false` resolved the issue.

**Comment by 7sDream** [comment]
Thanks for the infomation. I will add a small note in the document to indicate this.
